site_name: Puzzle Hunt Wiki CN
theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: 切换至深色模式

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换至浅色模式
  font:
    text: Noto Sans
    code: Source Code Pro
  language: zh
  icon:
    logo: material/puzzle
  favicon: _static/favicon.ico
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest

copyright: Copyright &copy; 2024 JCarlson

plugins:
  - privacy
  - search
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
  # - git-committers:
  #     repository: JimmyCHWang/puzzle-wiki-cn
  #     branch: master

extra:
  copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a>'
  pagetime: 'on'
  manifest: '_static/manifest.webmanifest'
  githash: ''
  status:
    frequent: 本页被标注为常用

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.smartsymbols

extra_css:
  - _static/css/extra.css

extra_javascript:
  - _static/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - PuzzleHunt 入门:
    - index.md
    - 关于 Puzzle Hunt: intro/about-puzzlehunt.md
    - PH 中的谜题: intro/a-puzzle-in-hunt.md
    - 如何解决一道谜题: intro/how-to-solve-a-puzzle.md
    - 备战 Puzzle Hunt: intro/be-prepared-for-hunt.md
    - 致谢: intro/acknowledgements.md
  - 密码与代码:
    - ciphers-and-codes/index.md
    - 密码 Ciphers: 
      - ciphers-and-codes/ciphers/index.md
      - A1Z26 字母序号: ciphers-and-codes/ciphers/a1z26.md
      - Atbash 埃特巴什: ciphers-and-codes/ciphers/atbash.md
      - Baconian 培根: ciphers-and-codes/ciphers/baconian.md
      - Base 进制转换: ciphers-and-codes/ciphers/base.md
      - Caesar 凯撒: ciphers-and-codes/ciphers/caesar.md
      - Columnar 列移位: ciphers-and-codes/ciphers/columnar.md
      - Keyboard 键盘: ciphers-and-codes/ciphers/keyboard.md
      - MonoAlphabetic 单表替换: ciphers-and-codes/ciphers/monoalphabetic.md
      - Pigpen 猪圈: ciphers-and-codes/ciphers/pigpen.md
      - Playfair 普莱费尔: ciphers-and-codes/ciphers/playfair.md
      - Polybius 棋盘: ciphers-and-codes/ciphers/polybius.md
      - Railfence 栅栏: ciphers-and-codes/ciphers/railfence.md
      - Reverse 倒序: ciphers-and-codes/ciphers/reverse.md
      - Scytale 密码棒: ciphers-and-codes/ciphers/scytale.md
      - Vigenere 维吉尼亚: ciphers-and-codes/ciphers/vigenere.md
    - 代码 Codes:
      - ciphers-and-codes/codes/index.md
      - Airport / Airlines 机场与航司: ciphers-and-codes/codes/airport.md
      - Alphabet 字母表: ciphers-and-codes/codes/alphabet.md
      - Area Codes 地区代码: ciphers-and-codes/codes/area-codes.md
      - ASCII: ciphers-and-codes/codes/ascii.md
      - Barcode / QR Code: ciphers-and-codes/codes/barcode-qrcode.md
      - Braille 布莱叶盲文: ciphers-and-codes/codes/braille.md
      - Chinese Encoding 中文相关代码: ciphers-and-codes/codes/chinese-encoding.md
      - Color Codes 颜色代码: ciphers-and-codes/codes/color-codes.md
      - Country Codes 国家代码: ciphers-and-codes/codes/country-codes.md
      - DNA: ciphers-and-codes/codes/dna.md
      - Maritime Flags 海事信号旗: ciphers-and-codes/codes/maritime-signal-flags.md
      - Morse 摩斯电码: ciphers-and-codes/codes/morse.md
      - Phonespell 手机键盘拼写: ciphers-and-codes/codes/phonespell.md
      - Phonetic Alphabet 音标字母: ciphers-and-codes/codes/phonetic-alphabet.md
      - Playing Cards 扑克牌: ciphers-and-codes/codes/playing-cards.md
      - Resistor Color 电阻颜色: ciphers-and-codes/codes/resistor-color.md
      - Semaphore 旗语: ciphers-and-codes/codes/semaphore.md
      - Unicode 万国码: ciphers-and-codes/codes/unicode.md
