site_name: Puzzle Hunt Wiki CN
theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: 切换至深色模式

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换至浅色模式
  font:
    text: Noto Sans
    code: Source Code Pro
  language: zh
  icon:
    logo: material/puzzle
  favicon: _static/favicon.ico
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest

copyright: Copyright &copy; 2024 JCarlson

plugins:
  - privacy
  - search
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
  # - git-committers:
  #     repository: JimmyCHWang/puzzle-wiki-cn
  #     branch: master

extra:
  copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a>'
  pagetime: 'on'
  manifest: '_static/manifest.webmanifest'
  githash: ''
  status:
    frequent: 本页被标注为常用

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.smartsymbols

extra_css:
  - _static/css/extra.css

extra_javascript:
  - _static/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - PuzzleHunt 入门:
    - index.md
    - 关于 Puzzle Hunt: intro/about-puzzlehunt.md
    - PH 中的谜题: intro/a-puzzle-in-hunt.md
    - 如何解决一道谜题: intro/how-to-solve-a-puzzle.md
    - 备战 Puzzle Hunt: intro/be-prepared-for-hunt.md
    - 致谢: intro/acknowledgements.md
  - 密码与代码:
    - ciphers-and-codes/index.md
    - 密码 Ciphers: 
      - ciphers-and-codes/ciphers/index.md
      - A1Z26: ciphers-and-codes/ciphers/a1z26.md
    - 代码 Codes:
      - ciphers-and-codes/codes/index.md
